"""
Repository / Interface Layer (typing only)
==========================================
Dieses Modul definiert ein Interface (Protocol) für den DB-Zugriff.

Ziel: Services hängen nicht mehr an der konkreten Implementierung
(`ORMDatenbankManager`), sondern nur an diesem Interface.

Das ist bewusst "leichtgewichtig": keine Runtime-Abhängigkeit, nur Typing.
"""

from __future__ import annotations

from typing import Dict, List, Optional, Protocol


class BibliothekRepository(Protocol):
    # Bücher
    def buch_speichern(self, titel: str, autor: str, isbn: str, jahr: int) -> bool: ...
    def buch_laden(self, isbn: str) -> Optional[Dict]: ...
    def alle_buecher_laden(self) -> List[Dict]: ...
    def bucher_suchen(self, suchbegriff: str) -> List[Dict]: ...
    def buch_bearbeiten(
        self,
        isbn: str,
        titel: str = None,
        autor: str = None,
        jahr: int = None,
        isbn_neu: str = None,
    ) -> bool: ...
    def buch_loeschen(self, isbn: str) -> bool: ...
    def beliebteste_buecher_laden(self, limit: int = 5) -> List[Dict]: ...
    def beliebte_buecher_karussell(self, limit: int = 5) -> List[Dict]: ...

    # Exemplare
    def exemplare_fuer_buch_anlegen(self, isbn: str, anzahl: int) -> bool: ...
    def verfuegbare_exemplare(self, isbn: str) -> List[Dict]: ...
    def exemplare_laden(self, isbn: str) -> List[Dict]: ...
    def exemplar_speichern(self, exemplar_id: str, isbn: str) -> bool: ...
    def exemplar_loeschen(self, exemplar_id: str) -> bool: ...
    def exemplar_status_aktualisieren(self, exemplar_id: str, status: str) -> bool: ...
    def exemplar_ausleihe_laden(self, exemplar_id: str) -> Optional[Dict]: ...

    # Benutzer
    def benutzer_speichern(
        self,
        benutzername: str,
        passwort: str,
        vorname: str,
        nachname: str,
        email: str,
        rolle: str = "Benutzer",
    ) -> bool: ...
    def benutzer_laden(self, benutzername: str) -> Optional[Dict]: ...
    def benutzer_mit_email_laden(self, email: str) -> Optional[Dict]: ...
    def alle_benutzer_laden(self) -> List[Dict]: ...
    def benutzer_passwort_aktualisieren(self, benutzername: str, passwort_hash: str) -> bool: ...

    # Ausleihen
    def ausleih_speichern(
        self,
        ausleih_id: str,
        benutzername: str,
        exemplar_id: str,
        ausleihdatum: str,
        faelligkeit: str,
    ) -> bool: ...
    def ausleih_laden(self, ausleih_id: str) -> Optional[Dict]: ...
    def ausleih_verlaengern(self, ausleih_id: str, neue_faelligkeit: str) -> bool: ...
    def ausleih_rueckgabe(self, ausleih_id: str) -> bool: ...
    def ausleihen_benutzer(self, benutzername: str) -> List[Dict]: ...
    def ueberfaellige_ausleihen(self) -> List[Dict]: ...
    def bald_faellige_ausleihen(self, tage: int = 7) -> List[Dict]: ...
    def benutzer_hat_ueberfaellige_buecher(self, benutzername: str) -> bool: ...

    # Merkliste
    def merkliste_eintrag_laden(self, benutzername: str, isbn: str) -> Optional[Dict]: ...
    def merkliste_eintrag_speichern(self, benutzername: str, isbn: str) -> bool: ...
    def merkliste_benutzer_laden(self, benutzername: str) -> List[Dict]: ...
    def merkliste_eintrag_loeschen(self, benutzername: str, isbn: str) -> bool: ...

